"""
Django settings for lif project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""

import os
import sys
from pathlib import Path

from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# Local defaults keep development friction low. Set these environment variables
# before deploying or running with shared data.
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "django-insecure-local-dev-only")

DEBUG = os.environ.get("DJANGO_DEBUG", "1") == "1"

LIF_REQUIRE_LOGIN = os.environ.get("LIF_REQUIRE_LOGIN", "0").strip().lower() in {"1", "true", "yes", "on"}

def _default_allowed_hosts():
    if os.environ.get("LIF_HOME_ASSISTANT_ADDON", "").strip().lower() in {"1", "true", "yes", "on"}:
        return "*"
    if os.environ.get("SUPERVISOR_TOKEN"):
        return "*"
    return "127.0.0.1,localhost"


ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get("DJANGO_ALLOWED_HOSTS", _default_allowed_hosts()).split(",")
    if host.strip()
]

# Full origins (with scheme) allowed to submit unsafe requests, e.g.
# "https://lif.example.com". Needed when the app is reached through a
# different origin than Django infers on its own, such as a Cloudflare
# Tunnel hostname.
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]

# Reverse proxies/tunnels (e.g. Cloudflare Tunnel) terminate TLS and forward
# plain HTTP, setting X-Forwarded-Proto to the original scheme. Only trust
# that header when explicitly told we're behind such a proxy, since blindly
# trusting it would let a client spoof "secure" on a direct connection.
if os.environ.get("DJANGO_TRUST_PROXY_SSL_HEADER", "0").strip().lower() in {"1", "true", "yes", "on"}:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    'planner.apps.PlannerConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'lif.middleware.HomeAssistantIngressMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'planner.middleware.RequireLoginMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'planner.middleware.PrivacyModeMiddleware',
    'planner.middleware.ReadOnlyModeMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

BACKUP_DIR = Path(os.environ.get("LIF_BACKUP_DIR", BASE_DIR / "backups"))

ROOT_URLCONF = 'lif.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'planner.context_processors.feature_flags',
            ],
        },
    },
]

WSGI_APPLICATION = 'lif.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': Path(os.environ.get("DJANGO_DB_PATH", BASE_DIR / 'db.sqlite3')),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', _('English')),
    ('de', _('German')),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = Path(os.environ.get("DJANGO_STATIC_ROOT", BASE_DIR / "staticfiles"))
WHITENOISE_MANIFEST_STRICT = False
USE_MANIFEST_STATICFILES = not DEBUG and "test" not in sys.argv

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage.CompressedManifestStaticFilesStorage"
            if USE_MANIFEST_STATICFILES
            else "django.contrib.staticfiles.storage.StaticFilesStorage"
        ),
    },
}

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'planner:dashboard'
LOGOUT_REDIRECT_URL = 'login'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
