from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from . import views

app_name = "planner"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("analytics/", views.analytics, name="analytics"),
    path("analytics/goals/", views.goal_planner, name="goal_planner"),
    path("assumptions/", views.assumptions_registry, name="assumptions_registry"),
    path("assumptions/reviews/", views.assumption_review_center, name="assumption_review_center"),
    path("assumptions/review/", views.assumption_review_edit, name="assumption_review_edit"),
    path("projection/integrity/", views.projection_integrity, name="projection_integrity"),
    path("income/", views.income_timeline, name="income_timeline"),
    path("quality/", views.data_quality, name="data_quality"),
    path("review/checklist/", views.planning_review_checklist, name="planning_review_checklist"),
    path("reconciliation/", views.reconciliation_center, name="reconciliation_center"),
    path("changes/", views.change_history, name="change_history"),
    path("changes/<int:pk>/", views.change_history_detail, name="change_history_detail"),
    path("attention/", views.attention_settings, name="attention_settings"),
    path("attention/hide/", views.attention_hide, name="attention_hide"),
    path("attention/restore/", views.attention_restore, name="attention_restore"),
    path("privacy-mode/", csrf_exempt(views.privacy_mode_toggle), name="privacy_mode_toggle"),
    path("system/", views.system_status, name="system_status"),
    path("system/backups/", views.backup_center, name="backup_center"),
    path("setup/", views.setup_wizard, name="setup"),
    path("onboarding/", views.onboarding, name="onboarding"),
    path("setup/real-data/start/", views.real_data_start, name="real_data_start"),
    path("setup/real-data/", views.real_data_readiness, name="real_data_readiness"),
    path("snapshots/", views.snapshots, name="snapshots"),
    path("snapshots/review/", views.snapshot_review, name="snapshot_review"),
    path("snapshots/projection-changes/", views.snapshot_projection_changes, name="snapshot_projection_changes"),
    path("snapshots/<int:pk>/compare/", views.snapshot_compare, name="snapshot_compare"),
    path("snapshots/<int:pk>/", views.snapshot_detail, name="snapshot_detail"),
    path("imports/", views.import_center, name="import_center"),
    path("imports/runbook/", views.import_runbook, name="import_runbook"),
    path("imports/moneymoney-mappings/", views.moneymoney_mappings, name="moneymoney_mappings"),
    path("imports/batches/<int:pk>/", views.import_batch_detail, name="import_batch_detail"),
    path("imports/<int:pk>/apply/", views.import_batch_apply, name="import_batch_apply"),
    path("exports/projection/monthly.csv", views.projection_monthly_export, name="projection_monthly_export"),
    path("exports/projection/yearly.csv", views.projection_yearly_export, name="projection_yearly_export"),
    path("exports/cash-flow.csv", views.cash_flow_export, name="cash_flow_export"),
    path("reports/", views.yearly_report, name="yearly_report"),
    path("reports/<int:year>/slides/", views.yearly_report_slides, name="yearly_report_slides"),
    path("projection/<int:month_index>/audit/", views.projection_audit, name="projection_audit"),
    path("projection/year/<int:year_index>/audit/", views.projection_year_audit, name="projection_year_audit"),
    path("retirement/", views.retirement_detail, name="retirement_detail"),
    path("household/", views.household_settings, name="household_settings"),
    path("household/<int:pk>/switch/", views.household_switch, name="household_switch"),
    path("household/<int:pk>/clone/", views.household_clone, name="household_clone"),
    path("household/<int:pk>/delete/", views.household_delete, name="household_delete"),
    path("setup/accounts/", views.account_setup, name="account_setup"),
    path("plan/", views.plan_index, name="plan_index"),
    path("plan/transfers/", views.transfer_plan, name="transfer_plan"),
    path("accounts/", views.account_index, name="account_index"),
    path("accounts/general-pool/", views.general_pool_detail, name="general_pool_detail"),
    path("accounts/general-pool/export.csv", views.general_pool_statement_export, name="general_pool_statement_export"),
    path("cash-goals/", views.cash_goal_index, name="cash_goal_index"),
    path("depot-holdings/", views.holding_index, name="holding_index"),
    path("debts/", views.debt_index, name="debt_index"),
    path("properties/", views.real_estate_index, name="real_estate_index"),
    path("retirement-plans/", views.retirement_plan_index, name="retirement_plan_index"),
    path("scenarios/compare/", views.scenario_compare, name="scenario_compare"),
    path("scenarios/clone-household/", views.scenario_household_clone, name="scenario_household_clone"),
    path("people/add/", views.person_create, name="person_create"),
    path("people/<int:pk>/edit/", views.person_update, name="person_update"),
    path("accounts/add/", views.account_create, name="account_create"),
    path("accounts/<int:pk>/", views.account_detail, name="account_detail"),
    path("accounts/<int:pk>/export.csv", views.account_statement_export, name="account_statement_export"),
    path("accounts/<int:pk>/edit/", views.account_update, name="account_update"),
    path("accounts/<int:pk>/delete/", views.account_delete, name="account_delete"),
    path("cash-goals/add/", views.cash_goal_create, name="cash_goal_create"),
    path("cash-goals/<int:pk>/edit/", views.cash_goal_update, name="cash_goal_update"),
    path("depot-holdings/add/", views.depot_holding_create, name="depot_holding_create"),
    path("depot-holdings/<int:pk>/edit/", views.depot_holding_update, name="depot_holding_update"),
    path("debts/add/", views.debt_create, name="debt_create"),
    path("debts/<int:pk>/", views.debt_detail, name="debt_detail"),
    path("debts/<int:pk>/edit/", views.debt_update, name="debt_update"),
    path("income-investments/add/", views.income_investment_create, name="income_investment_create"),
    path("income-investments/<int:pk>/edit/", views.income_investment_update, name="income_investment_update"),
    path("private-loans/add/", views.private_loan_create, name="private_loan_create"),
    path("private-loans/<int:pk>/edit/", views.private_loan_update, name="private_loan_update"),
    path("properties/add/", views.real_estate_create, name="real_estate_create"),
    path("properties/<int:pk>/edit/", views.real_estate_update, name="real_estate_update"),
    path("property-transfers/add/", views.real_estate_transfer_plan_create, name="real_estate_transfer_plan_create"),
    path(
        "property-transfers/<int:pk>/edit/",
        views.real_estate_transfer_plan_update,
        name="real_estate_transfer_plan_update",
    ),
    path("retirement-plans/add/", views.retirement_plan_create, name="retirement_plan_create"),
    path("retirement-plans/<int:pk>/edit/", views.retirement_plan_update, name="retirement_plan_update"),
    path("equity-grants/add/", views.equity_grant_create, name="equity_grant_create"),
    path("equity-grants/<int:pk>/edit/", views.equity_grant_update, name="equity_grant_update"),
    path("scenarios/add/", views.scenario_create, name="scenario_create"),
    path("scenarios/<int:pk>/edit/", views.scenario_update, name="scenario_update"),
    path("true-expenses/add/", views.true_expense_create, name="true_expense_create"),
    path("true-expenses/<int:pk>/edit/", views.true_expense_update, name="true_expense_update"),
    path("child-milestones/add/", views.child_milestone_create, name="child_milestone_create"),
    path("child-milestones/<int:pk>/edit/", views.child_milestone_update, name="child_milestone_update"),
    path("salary-changes/add/", views.salary_change_create, name="salary_change_create"),
    path("salary-changes/<int:pk>/edit/", views.salary_change_update, name="salary_change_update"),
    path("rules/add/", views.rule_create, name="rule_create"),
    path("rules/<int:pk>/edit/", views.rule_update, name="rule_update"),
    path("transfer-rules/add/", views.transfer_rule_create, name="transfer_rule_create"),
    path("transfer-rules/<int:pk>/edit/", views.transfer_rule_update, name="transfer_rule_update"),
    path("family-gifts/add/", views.family_gift_plan_create, name="family_gift_plan_create"),
    path("family-gifts/<int:pk>/edit/", views.family_gift_plan_update, name="family_gift_plan_update"),
    path("planned-investments/add/", views.planned_investment_purchase_create, name="planned_investment_purchase_create"),
    path(
        "planned-investments/<int:pk>/edit/",
        views.planned_investment_purchase_update,
        name="planned_investment_purchase_update",
    ),
]
