# Generated by Django 6.0.6 on 2026-06-13 12:52

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('account_type', models.CharField(choices=[('cash', 'Cash'), ('savings', 'Savings'), ('depot', 'Depot'), ('loan', 'Loan'), ('other', 'Other')], max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('ynab', 'YNAB')], default='manual', max_length=20)),
                ('institution', models.CharField(blank=True, max_length=120)),
                ('as_of_date', models.DateField(blank=True, null=True)),
                ('ynab_account_id', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='planner.household')),
            ],
            options={
                'ordering': ['account_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='moneyrule',
            name='target_account',
            field=models.ForeignKey(blank=True, help_text='Use this for transfers like ETF savings, where cash leaves but net worth stays.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_rules', to='planner.assetaccount'),
        ),
    ]
