# Generated by Django 6.0.6 on 2026-06-13 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_assetaccount_moneyrule_target_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepotHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('isin', models.CharField(blank=True, max_length=20)),
                ('ticker', models.CharField(blank=True, max_length=30)),
                ('asset_class', models.CharField(default='ETF', max_length=80)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=14)),
                ('latest_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('as_of_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='planner.assetaccount')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
