# Generated by Django 6.0.6 on 2026-06-13 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_depotholding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('current_principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('annual_interest_rate', models.DecimalField(decimal_places=2, help_text='Nominal annual interest rate in percent, for example 3.60.', max_digits=5)),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_month', models.DateField(blank=True, null=True)),
                ('end_month', models.DateField(blank=True, null=True)),
                ('fixed_interest_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(limit_choices_to={'account_type': 'loan'}, on_delete=django.db.models.deletion.CASCADE, related_name='debt', to='planner.assetaccount')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='planner.household')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
