# Generated by Django 6.0.6 on 2026-06-13 13:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_debt'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('investment_type', models.CharField(choices=[('solar', 'Solar'), ('private_loan', 'Private loan'), ('real_estate', 'Real estate'), ('other', 'Other')], default='other', max_length=30)),
                ('principal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('start_month', models.DateField()),
                ('end_month', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_investments', to='planner.household')),
            ],
            options={
                'ordering': ['start_month', 'name'],
            },
        ),
    ]
