# Generated by Django 6.0.6 on 2026-06-13 13:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_incomeinvestment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetirementPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('current_pension_points', models.DecimalField(decimal_places=3, help_text='Current German statutory pension points, according to Renteninformation.', max_digits=7)),
                ('expected_annual_points', models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Assumed yearly pension-point accrual until retirement.', max_digits=5)),
                ('pension_value_per_point', models.DecimalField(decimal_places=2, default=Decimal('40.79'), help_text='Monthly statutory pension value per point. Keep this editable.', max_digits=8)),
                ('private_monthly_pension', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Optional bAV, private pension, Riester, Ruerup, or similar monthly amount.', max_digits=12)),
                ('retirement_start_month', models.DateField()),
                ('end_month', models.DateField(blank=True, null=True)),
                ('annual_adjustment_rate', models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='Assumed yearly pension adjustment in percent after retirement starts.', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retirement_plans', to='planner.household')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retirement_plans', to='planner.person')),
            ],
            options={
                'ordering': ['retirement_start_month', 'person__name', 'name'],
            },
        ),
    ]
