# Generated by Django 6.0.6 on 2026-06-13 13:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_retirementplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquityGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('grant_type', models.CharField(choices=[('rsu', 'RSU'), ('stock_option', 'Stock option'), ('bonus_shares', 'Bonus shares'), ('other', 'Other')], default='rsu', max_length=30)),
                ('gross_vest_value', models.DecimalField(decimal_places=2, help_text='Expected gross value for each vesting event in household currency.', max_digits=12)),
                ('withholding_rate', models.DecimalField(decimal_places=2, default=Decimal('45.00'), help_text='Estimated taxes/social withholding in percent.', max_digits=5)),
                ('cadence', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='quarterly', max_length=20)),
                ('first_vest_month', models.DateField()),
                ('last_vest_month', models.DateField()),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_grants', to='planner.household')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_grants', to='planner.person')),
            ],
            options={
                'ordering': ['first_vest_month', 'person__name', 'name'],
            },
        ),
    ]
