# Generated by Django 6.0.6 on 2026-06-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_equitygrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='refinance_annual_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Assumed annual interest rate after refinancing.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='debt',
            name='refinance_from_month',
            field=models.DateField(blank=True, help_text='Optional override. If blank, refinancing starts the month after fixed interest ends.', null=True),
        ),
        migrations.AddField(
            model_name='debt',
            name='refinance_monthly_payment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Assumed monthly payment after refinancing.', max_digits=12, null=True),
        ),
    ]
