# Generated by Django 6.0.6 on 2026-06-14 07:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_debt_refinance_annual_interest_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('start_month', models.DateField()),
                ('end_month', models.DateField(blank=True, null=True)),
                ('monthly_cost_delta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('monthly_income_delta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_milestones', to='planner.person')),
            ],
            options={
                'ordering': ['start_month', 'person__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('start_month', models.DateField()),
                ('end_month', models.DateField(blank=True, null=True)),
                ('monthly_net_income_delta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_changes', to='planner.person')),
            ],
            options={
                'ordering': ['start_month', 'person__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('liquid_balance_delta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='One-time cash adjustment at the start of the scenario.', max_digits=12)),
                ('monthly_income_delta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Scenario-wide monthly income adjustment.', max_digits=12)),
                ('monthly_expense_delta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Scenario-wide monthly expense adjustment.', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='planner.household')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrueExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cadence', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('once', 'Once')], default='yearly', max_length=20)),
                ('first_due_month', models.DateField()),
                ('end_month', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='true_expenses', to='planner.household')),
            ],
            options={
                'ordering': ['first_due_month', 'name'],
            },
        ),
    ]
