# Generated by Django 6.0.6 on 2026-06-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_childmilestone_salarychange_scenario_trueexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='display_granularity',
            field=models.CharField(choices=[('auto', 'Auto'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='auto', max_length=20),
        ),
        migrations.AddField(
            model_name='household',
            name='planning_years',
            field=models.PositiveSmallIntegerField(default=0, help_text='Set this for long-term planning. Use 0 to keep the month-based horizon.'),
        ),
    ]
