# Generated by Django 6.0.6 on 2026-06-20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0010_household_display_granularity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CashGoal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(max_length=140),
                ),
                (
                    "annual_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Planned yearly household cash need in household currency.",
                        max_digits=12,
                    ),
                ),
                (
                    "start_year",
                    models.PositiveSmallIntegerField(help_text="First projection year this goal applies to."),
                ),
                (
                    "end_year",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Optional last year this goal applies to.",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_goals",
                        to="planner.household",
                    ),
                ),
            ],
            options={
                "ordering": ["start_year", "name"],
            },
        ),
    ]
