# Generated by Django 6.0.6 on 2026-06-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0011_cashgoal"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetaccount",
            name="depot_valuation",
            field=models.CharField(
                choices=[
                    ("account_balance", "Account balance"),
                    ("holdings_sum", "Sum of holdings"),
                ],
                default="account_balance",
                help_text="For depot accounts, choose whether projections use the account balance or summed holdings.",
                max_length=30,
            ),
        ),
    ]
