# Generated by Django 6.0.6 on 2026-06-20

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0012_assetaccount_depot_valuation"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetaccount",
            name="savings_annual_interest_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="For savings accounts, annual gross interest rate in percent.",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="assetaccount",
            name="savings_interest_cadence",
            field=models.CharField(
                choices=[
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("yearly", "Yearly"),
                ],
                default="monthly",
                help_text="For savings accounts, how often interest is paid.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="assetaccount",
            name="savings_interest_tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("25.00"),
                help_text="Simple tax rate applied to savings interest. Defaults to 25%.",
                max_digits=5,
            ),
        ),
    ]
