# Generated by Django 6.0.6 on 2026-06-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0013_assetaccount_savings_interest"),
    ]

    operations = [
        migrations.AddField(
            model_name="depotholding",
            name="payout_date",
            field=models.DateField(
                blank=True,
                help_text="Optional payout or maturity date, useful for individual bonds or target-maturity bond ETFs.",
                null=True,
            ),
        ),
    ]
