# Generated by Django 6.0.6 on 2026-06-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0014_depotholding_payout_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('snapshots', 'Snapshots'), ('moneymoney_import', 'Moneymoney Import'), ('ynab_import', 'Ynab Import'), ('multi_language', 'Multi Language'), ('advanced_tax_model', 'Advanced Tax Model'), ('docker_deployment', 'Docker Deployment'), ('mobile_read_only', 'Mobile Read Only')], max_length=80, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
