# Generated by Django 6.0.6 on 2026-06-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0016_alter_featureflag_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureflag',
            name='key',
            field=models.CharField(choices=[('analytics', 'Analytics'), ('cash_goals', 'Cash Goals'), ('depot_holdings', 'Depot Holdings'), ('debts', 'Debts'), ('income_investments', 'Income Investments'), ('retirement_plans', 'Retirement Plans'), ('equity_grants', 'Equity Grants'), ('scenarios', 'Scenarios'), ('true_expenses', 'True Expenses'), ('child_milestones', 'Child Milestones'), ('salary_changes', 'Salary Changes'), ('read_only_mode', 'Read Only Mode'), ('snapshots', 'Snapshots'), ('moneymoney_import', 'Moneymoney Import'), ('ynab_import', 'Ynab Import'), ('multi_language', 'Multi Language'), ('advanced_tax_model', 'Advanced Tax Model'), ('docker_deployment', 'Docker Deployment'), ('mobile_read_only', 'Mobile Read Only')], max_length=80, unique=True),
        ),
    ]
