# Generated by Django 6.0.6 on 2026-06-25 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0017_alter_featureflag_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureflag',
            name='key',
            field=models.CharField(choices=[('analytics', 'Analytics'), ('cash_goals', 'Cash Goals'), ('depot_holdings', 'Depot Holdings'), ('debts', 'Debts'), ('income_investments', 'Income Investments'), ('retirement_plans', 'Retirement Plans'), ('equity_grants', 'Equity Grants'), ('scenarios', 'Scenarios'), ('true_expenses', 'True Expenses'), ('child_milestones', 'Child Milestones'), ('salary_changes', 'Salary Changes'), ('imports', 'Imports'), ('read_only_mode', 'Read Only Mode'), ('snapshots', 'Snapshots'), ('moneymoney_import', 'Moneymoney Import'), ('ynab_import', 'Ynab Import'), ('multi_language', 'Multi Language'), ('advanced_tax_model', 'Advanced Tax Model'), ('docker_deployment', 'Docker Deployment'), ('mobile_read_only', 'Mobile Read Only')], max_length=80, unique=True),
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('csv_accounts', 'CSV accounts'), ('moneymoney', 'MoneyMoney'), ('ynab', 'YNAB')], max_length=30)),
                ('status', models.CharField(choices=[('dry_run', 'Dry run'), ('failed', 'Failed'), ('applied', 'Applied')], default='dry_run', max_length=20)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('valid_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='planner.household')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
