# Generated by Django 6.0.6 on 2026-06-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0018_alter_featureflag_key_importbatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbatch',
            name='source',
            field=models.CharField(choices=[('csv_accounts', 'CSV accounts'), ('csv_depot_holdings', 'CSV depot holdings'), ('moneymoney', 'MoneyMoney'), ('ynab', 'YNAB')], max_length=30),
        ),
    ]
