# Generated by Django 6.0.6 on 2026-06-25 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0019_alter_importbatch_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyMoneyAccountMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=140)),
                ('account_type', models.CharField(choices=[('cash', 'Cash'), ('savings', 'Savings'), ('depot', 'Depot'), ('loan', 'Loan'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moneymoney_account_mappings', to='planner.household')),
            ],
            options={
                'ordering': ['account_name'],
                'constraints': [models.UniqueConstraint(fields=('household', 'account_name'), name='unique_moneymoney_mapping_per_household')],
            },
        ),
    ]
