# Generated by Django 6.0.6 on 2026-06-26 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0021_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('review_date', models.DateField()),
                ('planned_summary', models.TextField(blank=True)),
                ('actual_summary', models.TextField(blank=True)),
                ('lessons_learned', models.TextField(blank=True)),
                ('next_actions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('baseline_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseline_reviews', to='planner.snapshot')),
                ('comparison_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_reviews', to='planner.snapshot')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_reviews', to='planner.household')),
            ],
            options={
                'ordering': ['-review_date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('household', 'baseline_snapshot', 'comparison_snapshot'), name='unique_snapshot_review_pair_per_household')],
            },
        ),
    ]
