# Generated by Django 6.0.6 on 2026-06-26 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0022_snapshotreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotReviewAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done'), ('skipped', 'Skipped')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_actions', to='planner.person')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='planner.snapshotreview')),
            ],
            options={
                'ordering': ['status', 'due_date', 'title'],
            },
        ),
    ]
