# Generated by Django 6.0.6 on 2026-06-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0026_household_retirement_tax_assumptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='data_mode',
            field=models.CharField(choices=[('demo', 'Demo'), ('real', 'Real')], default='real', max_length=20),
        ),
    ]
