# Generated by Django 6.0.6 on 2026-06-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0027_household_data_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='hidden_attention_items',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
