# Generated by Django 6.0.6 on 2026-06-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0028_household_hidden_attention_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashgoal',
            name='indexed_to_inflation',
            field=models.BooleanField(default=False, help_text='Increase this cash need from the start year using the household inflation assumption.'),
        ),
    ]
