# Generated by Django 6.0.6 on 2026-06-27 11:40

from django.db import migrations, models


def populate_moneymoney_source_keys(apps, schema_editor):
    MoneyMoneyAccountMapping = apps.get_model("planner", "MoneyMoneyAccountMapping")
    for mapping in MoneyMoneyAccountMapping.objects.filter(source_key=""):
        mapping.source_key = f"legacy-name:{mapping.account_name}"
        mapping.source_kind = "legacy"
        mapping.save(update_fields=["source_key", "source_kind"])


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0029_cashgoal_indexed_to_inflation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moneymoneyaccountmapping',
            options={'ordering': ['source_kind', 'account_name', 'source_key']},
        ),
        migrations.RemoveConstraint(
            model_name='moneymoneyaccountmapping',
            name='unique_moneymoney_mapping_per_household',
        ),
        migrations.AddField(
            model_name='assetaccount',
            name='moneymoney_account_key',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='moneymoneyaccountmapping',
            name='import_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='moneymoneyaccountmapping',
            name='source_key',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='moneymoneyaccountmapping',
            name='source_kind',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='assetaccount',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('moneymoney', 'MoneyMoney'), ('ynab', 'YNAB')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='moneymoneyaccountmapping',
            name='account_type',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('savings', 'Savings'), ('depot', 'Depot'), ('loan', 'Loan'), ('other', 'Other')], max_length=20),
        ),
        migrations.RunPython(populate_moneymoney_source_keys, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='assetaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('moneymoney_account_key', ''), _negated=True), fields=('household', 'moneymoney_account_key'), name='unique_moneymoney_account_key_per_household'),
        ),
        migrations.AddConstraint(
            model_name='moneymoneyaccountmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('source_key', ''), _negated=True), fields=('household', 'source_key'), name='unique_moneymoney_source_key_per_household'),
        ),
    ]
