# Generated by Django 6.0.6 on 2026-06-27 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0030_alter_moneymoneyaccountmapping_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyrule',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='planner.person'),
        ),
        migrations.AlterField(
            model_name='retirementplan',
            name='current_pension_points',
            field=models.DecimalField(decimal_places=4, help_text='Current German statutory pension points, according to Renteninformation.', max_digits=8),
        ),
    ]
