# Generated by Django 6.0.6 on 2026-06-27 14:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0031_alter_moneyrule_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetaccount',
            name='depot_annual_return_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Expected nominal annual depot return in percent. Used for projection growth; keep 0 for flat depot values.', max_digits=5),
        ),
    ]
