# Generated by Django 6.0.6 on 2026-06-27 17:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0032_assetaccount_depot_annual_return_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='annual_extra_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Optional yearly Sondertilgung paid on top of the monthly payment.', max_digits=12),
        ),
        migrations.AddField(
            model_name='debt',
            name='extra_payment_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Calendar month (1-12) the yearly extra payment is made. Defaults to the start month.', null=True),
        ),
        migrations.AddField(
            model_name='debt',
            name='interest_only_until',
            field=models.DateField(blank=True, help_text='Optional. Until this month only interest is paid and the principal does not reduce.', null=True),
        ),
    ]
