# Generated by Django 6.0.6 on 2026-06-27 21:18

import django.db.models.deletion
from django.db import migrations, models


def migrate_targeted_rules_to_transfer_rules(apps, schema_editor):
    MoneyRule = apps.get_model("planner", "MoneyRule")
    TransferRule = apps.get_model("planner", "TransferRule")
    targeted_rules = MoneyRule.objects.exclude(target_account_id=None)
    for rule in targeted_rules:
        TransferRule.objects.create(
            household_id=rule.household_id,
            person_id=rule.person_id,
            target_account_id=rule.target_account_id,
            name=rule.name,
            amount=rule.amount,
            cadence=rule.cadence,
            start_month=rule.start_month,
            end_month=rule.end_month,
            category=rule.category,
            notes=rule.notes,
            is_active=rule.is_active,
            created_at=rule.created_at,
            updated_at=rule.updated_at,
        )
    targeted_rules.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0033_debt_annual_extra_payment_debt_extra_payment_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cadence', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('start_month', models.DateField(blank=True, null=True)),
                ('end_month', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_rules', to='planner.household')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_rules', to='planner.person')),
                ('target_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfer_rules', to='planner.assetaccount')),
            ],
            options={
                'ordering': ['target_account__account_type', 'name'],
            },
        ),
        migrations.RunPython(migrate_targeted_rules_to_transfer_rules, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='moneyrule',
            name='target_account',
        ),
    ]
