# Generated by Django 6.0.6 on 2026-06-27 22:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0034_remove_moneyrule_target_account_transferrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateLoanReceivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('borrower', models.CharField(blank=True, max_length=140)),
                ('current_principal', models.DecimalField(decimal_places=2, help_text='Amount still owed to you today. Principal repayments reduce this receivable over time.', max_digits=12)),
                ('monthly_interest_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Freely entered monthly interest payment (Zins). Counts as income.', max_digits=12)),
                ('monthly_principal_repayment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Freely entered monthly principal repayment (Tilgung). Moves value from receivable to cash.', max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('start_month', models.DateField(blank=True, help_text='First repayment month. Leave blank if it applies immediately.', null=True)),
                ('end_month', models.DateField(blank=True, help_text='Optional final planned repayment month.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_loans', to='planner.household')),
            ],
            options={
                'ordering': ['start_month', 'name'],
            },
        ),
    ]
