# Generated by Django 6.0.6 on 2026-06-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0035_privateloanreceivable'),
    ]

    operations = [
        migrations.AddField(
            model_name='depotholding',
            name='payout_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional expected cash payout at maturity. Leave blank to use the current holding value.', max_digits=12, null=True),
        ),
    ]
