# Generated by Django 6.0.6 on 2026-06-28 08:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0037_alter_featureflag_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateloanreceivable',
            name='annual_interest_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Annual nominal interest rate in percent. If set, LiF calculates monthly net interest automatically.', max_digits=5),
        ),
        migrations.AddField(
            model_name='privateloanreceivable',
            name='interest_tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Tax rate applied to interest income, in percent.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='privateloanreceivable',
            name='monthly_interest_income',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Optional manual monthly net interest payment (Zins). Used when annual interest rate is 0.', max_digits=12),
        ),
    ]
