# Generated by Django 6.0.6 on 2026-06-28 14:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0038_privateloanreceivable_annual_interest_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetaccount',
            name='depot_annual_distribution_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='For depot accounts, expected annual cash distribution/dividend yield in percent, paid out (not reinvested) and taxed at the household capital-gains rate. This is separate from and on top of the price-growth assumption above; keep 0 for accumulating funds.', max_digits=5),
        ),
        migrations.AddField(
            model_name='assetaccount',
            name='depot_distribution_cadence',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='quarterly', help_text='For depot accounts, how often distributions are paid.', max_length=20),
        ),
    ]
