# Generated by Django 6.0.6 on 2026-06-28 17:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0039_assetaccount_depot_annual_distribution_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='default_income_growth_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Default annual growth for income rules and income investments when they do not override it.', max_digits=5),
        ),
        migrations.AddField(
            model_name='incomeinvestment',
            name='annual_growth_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Optional annual growth applied to monthly income. Leave blank to use the household default; set 0 to keep flat.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='moneyrule',
            name='annual_growth_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Optional annual growth applied to this amount. Leave blank to use the household default; set 0 to keep flat.', max_digits=5, null=True),
        ),
    ]
