# Generated by Django 6.0.6 on 2026-06-28 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0040_household_default_income_growth_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrule',
            name='source_account',
            field=models.ForeignKey(blank=True, help_text='Optional liquid account used as the funding source. Leave blank to use the general cash pool.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_transfer_rules', to='planner.assetaccount'),
        ),
    ]
