# Generated by Codex on 2026-06-28

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0041_transferrule_source_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="privateloanreceivable",
            name="source_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Cash or savings account that funded the loan and receives interest and principal repayments.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="private_loan_receivables",
                to="planner.assetaccount",
            ),
        ),
        migrations.AlterField(
            model_name="privateloanreceivable",
            name="end_month",
            field=models.DateField(
                blank=True,
                help_text="Planned final repayment month. Any remaining principal is repaid in this month.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="privateloanreceivable",
            name="monthly_principal_repayment",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Freely entered monthly principal repayment (Tilgung). Can be 0 if the full principal is repaid at the end.",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="transferrule",
            name="cadence",
            field=models.CharField(
                choices=[("monthly", "Monthly"), ("yearly", "Yearly"), ("once", "Once")],
                default="monthly",
                max_length=20,
            ),
        ),
    ]
