# Generated by Django 6.0.6 on 2026-06-28 21:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0042_private_loan_source_account_and_once_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='income_tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Optional planning rate for income tax and social security, applied only to income rules marked taxable. 0 leaves income rules as entered (net).', max_digits=5),
        ),
        migrations.AddField(
            model_name='moneyrule',
            name='is_taxable',
            field=models.BooleanField(default=False, help_text='For income rules, apply the household income-tax rate (treats the amount as gross). Leave off if the amount is already net.'),
        ),
    ]
