# Generated by Django 6.0.6 on 2026-06-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0043_household_income_tax_rate_moneyrule_is_taxable'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='fund_cash_goal_from_depot',
            field=models.BooleanField(default=False, help_text='When on, the yearly cash goal is treated as household spending and any shortfall after income is drawn from the depot, net of the capital-gains rate. Use this to model living off the portfolio. Avoid also modelling the same spending as separate expenses.'),
        ),
    ]
