# Generated by Django 6.0.6 on 2026-06-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0044_household_fund_cash_goal_from_depot'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateloanreceivable',
            name='disbursement_month',
            field=models.DateField(blank=True, help_text='Month the money is paid out from the source account. Leave blank if it was already lent (the principal already counts as a receivable and the source balance already reflects the outflow). Set a future month to keep the cash in the source account until then.', null=True),
        ),
    ]
