# Generated by Django 6.0.6 on 2026-06-29 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0045_privateloanreceivable_disbursement_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeinvestment',
            name='source_account',
            field=models.ForeignKey(blank=True, help_text='Cash or savings account the principal is paid from when the investment starts. Only applied to purchases at or after the projection start; leave blank for investments you already own and paid for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funded_income_investments', to='planner.assetaccount'),
        ),
    ]
