# Generated by Django 6.0.6 on 2026-06-29 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0046_incomeinvestment_source_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='default_operating_account',
            field=models.ForeignKey(blank=True, help_text='Default cash or savings account used for income and expense rules when a rule does not choose its own account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_households', to='planner.assetaccount'),
        ),
        migrations.AddField(
            model_name='moneyrule',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Optional cash or savings account this income lands in or this expense is paid from. Blank uses the household default operating account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='money_rules', to='planner.assetaccount'),
        ),
    ]
