# Generated by Django 6.0.6 on 2026-06-29 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0047_household_default_operating_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equitygrant',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Optional cash or savings account where net vesting proceeds land. Blank uses the household default operating account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equity_grants', to='planner.assetaccount'),
        ),
        migrations.AddField(
            model_name='salarychange',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Optional cash or savings account this salary delta lands in. Blank uses the household default operating account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_changes', to='planner.assetaccount'),
        ),
        migrations.AddField(
            model_name='trueexpense',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Optional cash or savings account this expense is paid from. Blank uses the household default operating account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='true_expenses', to='planner.assetaccount'),
        ),
    ]
