# Generated by Django 6.0.6 on 2026-06-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0048_equitygrant_account_salarychange_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateloanreceivable',
            name='is_gift',
            field=models.BooleanField(default=False, help_text='Money you will not get back (a gift or donation). It leaves your net worth when paid out instead of becoming a receivable — no interest or repayment.'),
        ),
    ]
