# Generated by Django 6.0.6 on 2026-06-29 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0050_realestate_alter_featureflag_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='source_account',
            field=models.ForeignKey(blank=True, help_text='Optional cash or savings account used for monthly payments and extra repayments. Blank uses the household default operating account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_debts', to='planner.assetaccount'),
        ),
    ]
