# Generated by Django 6.0.6 on 2026-06-29 22:24

from django.db import migrations, models


def mark_first_household_active(apps, schema_editor):
    Household = apps.get_model('planner', 'Household')
    household = Household.objects.order_by('pk').first()
    if household:
        household.is_active = True
        household.save(update_fields=['is_active'])


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0051_debt_source_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='is_active',
            field=models.BooleanField(default=False, help_text='The household currently shown by the planner. Only one household can be active.'),
        ),
        migrations.RunPython(mark_first_household_active, migrations.RunPython.noop),
    ]
