# Generated by Django 6.0.6 on 2026-06-29 22:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0052_household_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='capital_income_allowance',
            field=models.DecimalField(decimal_places=2, default=Decimal('2000.00'), help_text='Annual Sparerpauschbetrag applied to capital income before capital tax. Use 2,000 for a jointly planned household, or 1,000 for a single person.', max_digits=12),
        ),
    ]
