# Generated by Django 6.0.6 on 2026-06-30 06:16

import django.db.models.deletion
from django.db import migrations, models


def copy_mortgage_to_debt(apps, schema_editor):
    """Carry the existing single RealEstate.mortgage link over to the new
    Debt.real_estate reverse FK so no property loses its loan."""
    RealEstate = apps.get_model("planner", "RealEstate")
    for property_item in RealEstate.objects.exclude(mortgage__isnull=True):
        debt = property_item.mortgage
        debt.real_estate_id = property_item.id
        debt.save(update_fields=["real_estate"])


def unset_debt_real_estate(apps, schema_editor):
    """Reverse: restore the first linked debt as the property's mortgage."""
    RealEstate = apps.get_model("planner", "RealEstate")
    Debt = apps.get_model("planner", "Debt")
    for debt in Debt.objects.exclude(real_estate__isnull=True):
        RealEstate.objects.filter(pk=debt.real_estate_id, mortgage__isnull=True).update(mortgage_id=debt.id)


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0053_household_capital_income_allowance'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='real_estate',
            field=models.ForeignKey(blank=True, help_text='Optional property this loan finances. A property can have several loans; all are paid off when it is sold.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debts', to='planner.realestate'),
        ),
        migrations.RunPython(copy_mortgage_to_debt, unset_debt_real_estate),
        migrations.RemoveField(
            model_name='realestate',
            name='mortgage',
        ),
    ]
