# Generated by Django 6.0.6 on 2026-06-30 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0054_remove_realestate_mortgage_debt_real_estate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedInvestmentPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('asset_type', models.CharField(choices=[('etf', 'ETF'), ('stock', 'Stock'), ('bond', 'Bond'), ('other', 'Other')], default='etf', max_length=20)),
                ('isin', models.CharField(blank=True, max_length=20)),
                ('ticker', models.CharField(blank=True, max_length=30)),
                ('purchase_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_month', models.DateField(help_text='Month when the planned purchase should happen.')),
                ('payout_date', models.DateField(blank=True, help_text='Optional maturity or payout date, most useful for bonds and target-maturity ETFs.', null=True)),
                ('payout_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Optional expected cash payout at maturity. Leave blank to use the purchase amount.', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_investment_purchases', to='planner.household')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planned_investment_purchases', to='planner.person')),
                ('source_account', models.ForeignKey(blank=True, help_text='Optional cash or savings account used to fund the purchase. Leave blank to use the general liquid pool.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funded_investment_purchases', to='planner.assetaccount')),
                ('target_account', models.ForeignKey(help_text='Depot account that will receive the planned purchase.', on_delete=django.db.models.deletion.CASCADE, related_name='planned_investment_purchases', to='planner.assetaccount')),
            ],
            options={
                'ordering': ['purchase_month', 'name'],
            },
        ),
    ]
