# Generated by Django 6.0.6 on 2026-06-30 09:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0055_plannedinvestmentpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetaccount',
            name='depot_teilfreistellung_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='German partial tax exemption for depot distributions and gains. Use 30% for equity funds, 0% for bonds, or an average for mixed depots.', max_digits=5),
        ),
    ]
