# Generated by Django 6.0.6 on 2026-06-30 09:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0056_assetaccount_depot_teilfreistellung_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetaccount',
            name='depot_vorabpauschale_enabled',
            field=models.BooleanField(default=False, help_text='Apply German Vorabpauschale planning tax for accumulating funds. Usually off for distributing funds or bonds.'),
        ),
        migrations.AddField(
            model_name='household',
            name='vorabpauschale_basiszins_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.20'), help_text='Planning Basiszins for German Vorabpauschale in percent. Update when the official annual rate changes.', max_digits=5),
        ),
    ]
