# Generated by Django 6.0.6 on 2026-06-30 09:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0057_assetaccount_depot_vorabpauschale_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='emergency_fund_months',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Target months of recurring expenses to keep liquid. Set 0 to disable emergency-fund checks.', max_digits=5),
        ),
    ]
