# Generated by Django 6.0.6 on 2026-06-30 09:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0058_household_emergency_fund_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='retirementplan',
            name='contribution_end_month',
            field=models.DateField(blank=True, help_text='Optional last contribution month. If blank, contributions stop before retirement starts.', null=True),
        ),
        migrations.AddField(
            model_name='retirementplan',
            name='contribution_relief_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Simple tax/social-security relief on contributions. A 100 EUR contribution with 35% relief costs 65 EUR net cash.', max_digits=5),
        ),
        migrations.AddField(
            model_name='retirementplan',
            name='contribution_start_month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='retirementplan',
            name='monthly_contribution',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Optional gross monthly contribution before retirement. Leave 0 if already reflected in net salary.', max_digits=12),
        ),
        migrations.AddField(
            model_name='retirementplan',
            name='payout_health_insurance_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Share of pension payout exposed to the household health/care insurance assumption.', max_digits=5),
        ),
        migrations.AddField(
            model_name='retirementplan',
            name='payout_taxable_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Share of pension payout exposed to the household pension tax, church tax, and solidarity assumptions.', max_digits=5),
        ),
        migrations.AddField(
            model_name='retirementplan',
            name='vehicle_type',
            field=models.CharField(choices=[('statutory', 'Statutory pension / generic'), ('private', 'Private pension'), ('direktversicherung', 'Direktversicherung'), ('riester', 'Riester'), ('ruerup', 'Ruerup / Basisrente'), ('bav', 'bAV')], default='statutory', help_text='Planning category for German retirement vehicles. Defaults preserve the current generic net-pension behavior.', max_length=32),
        ),
    ]
