# Generated by Django 6.0.6 on 2026-06-30 10:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0059_retirementplan_contribution_end_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='saved_monthly_rent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Residence only. Optional imputed rent saving used to offset a modeled rent expense for rent-vs-buy comparisons.', max_digits=12),
        ),
    ]
