# Generated by Django 6.0.6 on 2026-07-03 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0060_realestate_saved_monthly_rent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], max_length=20)),
                ('model_name', models.CharField(max_length=120)),
                ('object_pk', models.CharField(blank=True, max_length=64)),
                ('object_label', models.CharField(blank=True, max_length=220)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(default='model', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_log_entries', to='planner.household')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['household', '-created_at'], name='planner_cha_househo_f56eb2_idx'), models.Index(fields=['model_name', 'object_pk'], name='planner_cha_model_n_a6da8d_idx')],
            },
        ),
    ]
