# Generated by Django 6.0.6 on 2026-07-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0061_changelogentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='is_baseline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='snapshot_type',
            field=models.CharField(choices=[('baseline', 'Baseline'), ('annual', 'Annual'), ('pre_import', 'Pre-import'), ('manual', 'Manual')], default='manual', max_length=20),
        ),
    ]
