# Generated by Django 6.0.6 on 2026-07-03 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0062_snapshot_is_baseline_snapshot_snapshot_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changelogentry',
            name='source',
        ),
    ]
