# Generated by Django 6.0.6 on 2026-07-04 09:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0064_backfill_baseline_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='depotholding',
            name='annual_distribution_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Expected annual cash distribution/dividend yield in percent for this specific holding, paid out (not reinvested) and taxed at the household capital-gains rate. Only used when the depot is valued by summed holdings; keep 0 for accumulating funds. Not a growth assumption -- see the depot's own return rate for that.", max_digits=5),
        ),
        migrations.AddField(
            model_name='depotholding',
            name='distribution_cadence',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='quarterly', help_text='How often this holding pays its distribution.', max_length=20),
        ),
    ]
