# Generated by Django 6.0.6 on 2026-07-04 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0066_backfill_holding_distribution_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetaccount',
            name='counts_in_household_net_worth',
            field=models.BooleanField(default=True, help_text='Include this account in household planning net worth, liquidity, FIRE, and retirement projections. Turn off for child-owned depots.'),
        ),
        migrations.AddField(
            model_name='assetaccount',
            name='owner_person',
            field=models.ForeignKey(blank=True, help_text='Person owner for child or individual accounts.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_accounts', to='planner.person'),
        ),
        migrations.AddField(
            model_name='assetaccount',
            name='owner_type',
            field=models.CharField(choices=[('household', 'Household'), ('person', 'Person'), ('external', 'External / informational')], default='household', help_text='Who legally owns this account. Child-owned accounts can be tracked without counting toward household retirement net worth.', max_length=20),
        ),
    ]
