# Generated by Django 6.0.6 on 2026-07-04 13:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0067_assetaccount_counts_in_household_net_worth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyGiftPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gift_month', models.DateField(help_text='Month when the gift is applied once in the forecast.')),
                ('allowance_amount', models.DecimalField(decimal_places=2, default=Decimal('400000.00'), help_text='Planning allowance for this giver-recipient relationship in the current 10-year German gift-tax window.', max_digits=12)),
                ('allowance_window_years', models.PositiveSmallIntegerField(default=10, help_text='German gift-tax planning window. Gifts from the same giver to the same recipient are normally considered over 10 years.')),
                ('purpose', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_gift_plans', to='planner.person')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_gift_plans', to='planner.household')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_gift_plans', to='planner.person')),
                ('source_account', models.ForeignKey(blank=True, help_text='Optional cash or savings account funding the gift. Leave blank to use the general liquid pool.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funded_family_gifts', to='planner.assetaccount')),
                ('target_account', models.ForeignKey(help_text='Child-owned account receiving the gift, such as a Kinderdepot.', on_delete=django.db.models.deletion.CASCADE, related_name='received_family_gifts', to='planner.assetaccount')),
            ],
            options={
                'ordering': ['gift_month', 'recipient__name', 'giver__name', 'name'],
            },
        ),
    ]
