# Generated by Django 6.0.6 on 2026-07-04 13:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0068_familygiftplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateTransferPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('transfer_month', models.DateField(help_text='Month when ownership leaves the household planning balance sheet.')),
                ('ownership_percent', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Percent of the property transferred. The first version applies this as a proportional net-worth reduction.', max_digits=5)),
                ('taxable_gift_value', models.DecimalField(decimal_places=2, help_text='Planning value counted against the gift allowance after Nießbrauch or other valuation reductions. Enter explicitly.', max_digits=12)),
                ('allowance_amount', models.DecimalField(decimal_places=2, default=Decimal('400000.00'), help_text='Planning allowance for this giver-recipient relationship in the current 10-year German gift-tax window.', max_digits=12)),
                ('allowance_window_years', models.PositiveSmallIntegerField(default=10)),
                ('retained_niessbrauch', models.BooleanField(default=False, help_text='If enabled, the household keeps the residence saved-rent benefit after the ownership transfer.')),
                ('niessbrauch_annual_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Optional annual value of the retained Nießbrauch used as documentation for the taxable gift value.', max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_property_transfer_plans', to='planner.person')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_transfer_plans', to='planner.household')),
                ('property_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_plans', to='planner.realestate')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_property_transfer_plans', to='planner.person')),
            ],
            options={
                'ordering': ['transfer_month', 'property_item__name', 'recipient__name'],
            },
        ),
    ]
