# Generated by Django 6.0.6 on 2026-07-05 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0069_realestatetransferplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssumptionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=220)),
                ('label', models.CharField(max_length=220)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=120)),
                ('note', models.TextField(blank=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assumption_reviews', to='planner.household')),
            ],
            options={
                'ordering': ['key'],
                'indexes': [models.Index(fields=['household', 'key'], name='planner_ass_househo_c56403_idx'), models.Index(fields=['household', 'reviewed_at'], name='planner_ass_househo_940ac4_idx')],
                'constraints': [models.UniqueConstraint(fields=('household', 'key'), name='unique_assumption_review_per_household_key')],
            },
        ),
    ]
