# Generated by Django 6.0.6 on 2026-07-05 18:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0070_assumption_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedinvestmentpurchase',
            name='annual_distribution_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Expected annual cash distribution/dividend yield in percent for this specific purchase, paid out (not reinvested) and taxed at the household capital-gains rate. Only used when the target depot is valued by summed holdings; keep 0 for accumulating funds.', max_digits=5),
        ),
        migrations.AddField(
            model_name='plannedinvestmentpurchase',
            name='distribution_cadence',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='quarterly', help_text='How often this purchase pays its distribution, once acquired.', max_length=20),
        ),
    ]
